// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIuAWx-VLaB67kIouqj8bmiJBa4BLZci8',
    appId: '1:920557202713:web:c238133877bec73c236988',
    messagingSenderId: '920557202713',
    projectId: 'device-streaming-34b59fe4',
    authDomain: 'device-streaming-34b59fe4.firebaseapp.com',
    storageBucket: 'device-streaming-34b59fe4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4S-d4hpKMJ7QrBzt-4g7Vswf41gzxRbE',
    appId: '1:920557202713:android:7acf740cba04dc1a236988',
    messagingSenderId: '920557202713',
    projectId: 'device-streaming-34b59fe4',
    storageBucket: 'device-streaming-34b59fe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbo7oGpsCfvgAYZKgCtKRwTg_8zi2PT7o',
    appId: '1:920557202713:ios:7e14d1f189cfeba1236988',
    messagingSenderId: '920557202713',
    projectId: 'device-streaming-34b59fe4',
    storageBucket: 'device-streaming-34b59fe4.firebasestorage.app',
    iosBundleId: 'com.example.ungdungDatMonAn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbo7oGpsCfvgAYZKgCtKRwTg_8zi2PT7o',
    appId: '1:920557202713:ios:7e14d1f189cfeba1236988',
    messagingSenderId: '920557202713',
    projectId: 'device-streaming-34b59fe4',
    storageBucket: 'device-streaming-34b59fe4.firebasestorage.app',
    iosBundleId: 'com.example.ungdungDatMonAn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIuAWx-VLaB67kIouqj8bmiJBa4BLZci8',
    appId: '1:920557202713:web:757c4ddb751099a7236988',
    messagingSenderId: '920557202713',
    projectId: 'device-streaming-34b59fe4',
    authDomain: 'device-streaming-34b59fe4.firebaseapp.com',
    storageBucket: 'device-streaming-34b59fe4.firebasestorage.app',
  );
}
